API_KEY_FILE: cfg/api_key.yaml
DB_FILE: db/gpt3sql.sqlite
Input_prefix: 'input: '
Input_suffix: '

  '
Maximum_length: 256
Mode:
- Complete
Model:
- code-davinci-002
- text-davinci-002
- text-davinci-001
- text-curie-001
- text-babbage-001
- text-ada-001
- davinci-instruct-beta
- code-cushman-001
- code-davinci-001
Output_prefix: 'output: '
Output_suffix: '


  '
Temperature: 0.1
