## Playground Settings

Mode:
  - Complete
  - Insert
  - Edit

Model:
  - davinci-instruct-beta
  - text-davinci-002
  - text-davinci-001

Temperature: 0.1
Maximum_length: 256
Input_prefix: "input: "
Input_suffix: "\n"
Output_prefix: "output: "
Output_suffix: "\n\n"


# ENTER_YOUR_OWN_KEY_HERE
OPENAI_API_KEY: <ENTER-Your-Own-API-Key>

# Database to store OpenAI request/responses
DB_FILE: db/gpt3sql.sqlite

